spring.application.name=sistema-biblioteca

spring.datasource.url=jdbc:h2:mem:biblioteca
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.datasource.initialization-mode=always

spring.messages.basename=messages
spring.jpa.defer-datasource-initialization=true

# Logs
logging.level.com.biblioteca=DEBUG
logging.file.name=logs/biblioteca.log
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.defaultModelsExpandDepth=-1

server.error.include-message=always
server.error.include-binding-errors=always

# Nível de log
logging.level.root=INFO
logging.level.com.biblioteca.sistema_biblioteca=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Ativar endpoints do Actuator
management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers
management.endpoint.health.show-details=always