spring.application.name=sistema-biblioteca
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_db1?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.h2.console.enabled=false

spring.messages.basename=messages
spring.jpa.defer-datasource-initialization=true

# Logs
logging.level.com.biblioteca=DEBUG
logging.file.name=logs/biblioteca.log
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.defaultModelsExpandDepth=-1

server.error.include-message=always
server.error.include-binding-errors=always

# Nivel de log
logging.level.root=INFO
logging.level.com.biblioteca.sistema_biblioteca=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Ativar endpoints do Actuator
management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers
management.endpoint.health.show-details=always

# ===============================
#  CONFIGURACAO DE E-MAIL (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gui.svalerio2005@gmail.com
spring.mail.password=ahqrhyhmslizqjin
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
spring.mail.from=gui.svalerio2005@gmail.com
spring.mail.properties.mail.debug=true

# ===============================
#  LIMITE DE UPLOAD DE ARQUIVOS
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
biblioteca.upload.dir=C:/Users/astronyx/Documents/sistema-biblioteca/uploads

# ===============================
#  LOGS
# ===============================
logging.level.org.springframework.mail=INFO
logging.level.com.biblioteca.sistema_biblioteca.service.EmailService=INFO
