# test profile overrides
#spring.profiles.active=test

# Use H2 in-memory isolated for tests

# Disable scheduling in tests (prevents scheduler running while tests start)
spring.scheduling.enabled=false

# Allow bean overriding in tests (handy when tests create beans with same name)
spring.main.allow-bean-definition-overriding=true

# Disable swagger UI autoconfig in tests (if that caused conflicts)
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.datasource.url=jdbc:h2:mem:biblioteca-test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=false
spring.sql.init.mode=never

# Messages
spring.messages.basename=messages
